name = "chicken-road-review-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chicken-road-review.net"
HMAC_KEY = "dab723f256686306044055d6c936511060d8c0445a3688cdd5db6f7505b774f9"
COOKIE_NAME = "ik9"
PLAY_PATH = "play-now"
BUTTON_ID = "pfcfe8688cfd6856dbf6982ac5e2d53c7"
GATE_SALT = "085ff13d9ba4d170"
